### ISSUE TITLE
Update requirements for 9.0.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cupy-feedstock#101]
There are some changes to the requirements coming up. Noting them here so we remember 🙂 

https://github.com/cupy/cupy/pull/4631
https://github.com/cupy/cupy/pull/4632

**Comment by leofang** [comment]
Nice. We can try bumping them in the next rc release.

**Comment by leofang** [comment]
shoot I forgot this!

**Comment by jakirkham** [comment]
Ack! I did too.

We can add them in a new PR with a build number bump

**Comment by jakirkham** [comment]
Handling in PR ( https://github.com/conda-forge/cupy-feedstock/pull/107 ). Also found a few things we can update for 8.5.0 in PR ( https://github.com/conda-forge/cupy-feedstock/pull/108 )

**Comment by jakirkham** [comment]
Oops wrong button 😬

Think we can keep this open until 9.0.0 is out
