### ISSUE TITLE
 conda install cupy installs wrong toolkit version with CUDA 11.0 on Windows

### ISSUE THREAD

**Issue by thomasaarholt** [conda-forge/cupy-feedstock#128]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
`conda create --name cutest cupy` installs toolkit version 11.2 when I have CUDA 11.0 installed. This raises the error below.
`conda create --name cutest2 cupy cudatoolkit=11.0` works fine.

Ideally, conda would check which `cudatoolkit` version should be installed. Is this currently possible?
If not - would it be possible to check that the versions match on `import cupy`, and then raise a more useful error?

I check CUDA version by `nvcc --version`: version 11.0 is installed (using 11.0 for compatability reasons with other software)

Both `cp.linspace(0, 10, 10)` and `cp.show_config()` result in essentially the same error:

```python
$ python -c 'import cupy; cupy.show_config()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupy\__init__.py", line 860, in show_config
    _sys.stdout.write(str(_cupyx.get_runtime_info()))
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 277, in get_runtime_info
    return _RuntimeInfo()
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 156, in __init__
    self.cublas_version = _eval_or_error(
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 64, in _eval_or_error
    return func()
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 158, in <lambda>
    cupy.cuda.device.get_cublas_handle()),
  File "cupy\cuda\device.pyx", line 46, in cupy.cuda.device.get_cublas_handle
  File "cupy\cuda\device.pyx", line 47, in cupy.cuda.device.get_cublas_handle
  File "cupy\cuda\device.pyx", line 29, in cupy.cuda.device._get_device
  File "cupy_backends\cuda\api\runtime.pyx", line 289, in cupy_backends.cuda.api.runtime.getDevice
  File "cupy_backends\cuda\api\runtime.pyx", line 261, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

* Conditions (you can just paste the output of `python -c 'import cupy; cupy.show_config()'`)
  - The above call results in the same error.
  - CuPy version: 9.0.0
  - OS/Platform: Windows 10 v1909
  - CUDA version: 11.0

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\thomasaar\Miniconda3\envs\cutest:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.4.13            haa95532_1
certifi                   2020.12.5        py39hcbf5309_1    conda-forge
cudatoolkit               11.2.2               h933977f_8    conda-forge
cupy                      9.0.0            py39hc474d4a_1    conda-forge
fastrlock                 0.6              py39h415ef7b_0    conda-forge
intel-openmp              2021.2.0           h57928b3_616    conda-forge
libblas                   3.9.0                     9_mkl    conda-forge
libcblas                  3.9.0                     9_mkl    conda-forge
liblapack                 3.9.0                     9_mkl    conda-forge
mkl                       2021.2.0           hb70f87d_389    conda-forge
numpy                     1.20.2           py39h6635163_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
python                    3.9.4           h7840368_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
setuptools                52.0.0           py39haa95532_0
sqlite                    3.35.5               h8ffe710_0    conda-forge
tbb                       2021.2.0             h2d74725_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py39hcbf5309_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : cutest
    active env location : C:\Users\thomasaar\Miniconda3\envs\cutest
            shell level : 3
       user config file : C:\Users\thomasaar\.condarc
 populated config files : C:\Users\thomasaar\.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.3=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\thomasaar\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\thomasaar\Miniconda3\pkgs
                          C:\Users\thomasaar\.conda\pkgs
                          C:\Users\thomasaar\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\thomasaar\Miniconda3\envs
                          C:\Users\thomasaar\.conda\envs
                          C:\Users\thomasaar\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.5 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by leofang** [comment]
Thanks for the detailed report @thomasaarholt. I can see that you have the latest CUDA driver (for 11.3) installed.

> Ideally, conda would check which `cudatoolkit` version should be installed. Is this currently possible?

No. Both Anaconda and Conda-Forge provide CUDA runtime libraries in `cudatoolkit`, which ideally would work with any compatible driver (the driver is backward compatible). Therefore, what Conda does is that it checks your driver version, and chooses to install the latest CUDA version that the driver supports. In your case, in particular, you driver should support any CUDA version (Conda-Forge currently provides up to CUDA 11.2), which was why it picked 11.2.

@conda-forge/core @conda-forge/cupy @jakirkham @kkraus14 My wild guess for this error is it relates to how DLL on Windows is searched. For some reason:
- The system CUDA (CUDA 11.0) was found and picked up
- The 11.0 DLL is incompatible with CUDA 11.2 (Why? Don't we have forward compatibility since CUDA 11?)

By the way, according to the error log:
```
  File "C:\Users\thomasaar\Miniconda3\envs\cutest\lib\site-packages\cupyx\_runtime.py", line 158, in <lambda>
    cupy.cuda.device.get_cublas_handle()),
```
The loading of CUDA driver and runtime libraries (`libcuda` and `libcudart`; not sure what they're called on Windows) were done correctly.

> If not - would it be possible to check that the versions match on `import cupy`, and then raise a more useful error?

If this is a linking problem, it is actually very hard to do, as you need to call some CUDA API but due the the linking error these APIs might not be available. There is a (stalling) discussion on a similar request: https://github.com/cupy/cupy/issues/3403#issuecomment-640350581, https://github.com/cupy/cupy/issues/1268

**Comment by leofang** [comment]
> `conda create --name cutest cupy` installs toolkit version 11.2 when I have CUDA 11.0 installed.

It may be late to ask, but I just read the thread again and have a question: @thomasaarholt did you mean you had CUDA 11.0 installed outside of conda; that is, it was not `cudatoolkit` 11.0 but a local CUDA installation? If so, the conda solver has no way to tell. Everything must be visible to the solver. If you had `cudatoolkit` 11.0 installed, when you installed `cupy` from conda-forge it would not be updated to 11.2; the solver would pick the compatible version of `cupy` to install.

**Comment by thomasaarholt** [comment]
I am afraid I cannot remember. :/ this is no longer a problem for me. Happy to close unless you think it should stay open for some reason.

**Comment by leofang** [comment]
Thanks!
