### ISSUE TITLE
Add custom labels to the recipe to indicate CUDA version?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#13]
Just found that rapidsai has its own CuPy recipe: 
https://anaconda.org/rapidsai/cupy/files
They have custom labels to indicate against which version of CUDA the recipe is built. I think this is a nice feature because it's impossible to tell this from the build string. How do we add this?

btw, @jakirkham, any chance you know who is maintaining rapidsai's recipes?

**Comment by leofang** [comment]
I looked at the conda-forge infrastructure, and to do this we'd need to submit a PR to conda smithy and modify the build script. Don't think it worth the effort...

**Comment by jakirkham** [comment]
Ah sorry! I completely missed this.

RAPIDS did use labels, but we moved away from that in favor of the `cudatoolkit` versioned approach that we have also adopted here. The relevant discussion is in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/687 ).

**Comment by leofang** [comment]
Cool, thanks for the pointer John!
