### ISSUE TITLE
Build CuPy for PowerPC?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#14]
Continuing the discussion in https://github.com/cupy/cupy/issues/2583#issuecomment-553603461. 

@jakirkham @isuruf Do we have the compiler/docker/CI infrastructure for this task? A while ago I verified on Ascent (Summit's test node) that CuPy works on PowerPC, so it's just a matter of preparing and building.

cc: @berceanu

**Comment by leofang** [comment]
It seems we need conda-forge/nvcc-feedstock#21 to be closed first.

**Comment by leofang** [comment]
cf: AnacondaRecipes/cudatoolkit-feedstock#4

**Comment by leofang** [comment]
Pending https://github.com/AnacondaRecipes/cudatoolkit-feedstock/pull/6 and https://github.com/conda-forge/docker-images/issues/141.

**Comment by jakirkham** [comment]
The `nvcc` bit is easy once we have `cudatoolkit`.

**Comment by jakirkham** [comment]
Now we just need to figure out how to get the older versions in there 🙂

https://github.com/AnacondaRecipes/cudatoolkit-feedstock/issues/8

**Comment by leofang** [comment]
Can we build on top of CF's Power8 cudatoolkit instead? https://github.com/conda-forge/cudatoolkit-feedstock/pull/6

**Comment by jakirkham** [comment]
Right now we are still building out `cudatoolkit` versions. There's also some integration work needed. That said, yeah I think that should be possible.

**Comment by leofang** [comment]
@jakirkham How close we are to build for ppcle64? I lost track...

**Comment by leofang** [comment]
Looks like updating pinning is the last missing piece? https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/725

**Comment by jakirkham** [comment]
Maybe @jaimergp would know 😉

**Comment by jaimergp** [comment]
Hi! Yes, it's been on my list for a while, but it got deprioritized after finding out OpenMM has some issues on GCC9+PPC, so I focused on other things while those are solved. 

I can work on it after I am done with https://github.com/conda-forge/nvcc-feedstock/pull/59.

IIRC, we need:

- [ ] `nvcc` packages
- [ ] build `cudatoolkit` under x.y version (they didn't get built because of some issue with files being somewhere else wrt linux 64)
- [ ] update the pinnings

**Comment by leofang** [comment]
Note to self: cuSPARSELt currently does not support ppc64le.

**Comment by leofang** [comment]
Support for ppc64le + CUDA 10.2 is done for v9.2.0 (#134) and v10.0.0a2 (#135). Thank you @jaimergp again for making the infrastructure available!

**Comment by leofang** [comment]
Hi all, I am reopening this issue for discussion. I've been monitoring CuPy's download counts regularly, and I noticed the download counts have been consistently on the order of 15 for every version (Python x CUDA) on ppc64le, making me suspect we have almost no human user of the ppc64le packages. If it's the case, we should consider to not build them so as to save CI and anaconda.org resources.

**Comment by leofang** [comment]
Let me start by shrinking the build matrix for ppc64le.
