### ISSUE TITLE
9.2.0 with support of cuda11.3?

### ISSUE THREAD

**Issue by gbwg** [conda-forge/cupy-feedstock#140]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
Since cupy 9.2.0  supports cuda 11.3 now， but this feature is still not available on conda-forge. The latest supported cuda is  11.2. Could you please upload a version supporting cuda 11.3. Thanks. 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by leofang** [comment]
Hi @gbwg, the short answer is we will, eventually. However, there are a number of infrastructural changes pending (ex: https://github.com/conda-forge/cudatoolkit-feedstock/pull/60) that block the support of CUDA 11.3+ and it's under active discussion. Before that, all downstream feedstocks just have to wait ftm I am afraid.
