### ISSUE TITLE
Support CUDA 10.2

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#15]
Mirroring cupy/cupy#2667.

**Comment by jakirkham** [comment]
Thanks for raising Leo.

We are currently working on this in conda-forge. Please see this issue ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/361 ) for tracking info.

It would be good to hear back on this question ( https://github.com/cupy/cupy/issues/2667#issuecomment-566767421 ) as well.

**Comment by jakirkham** [comment]
Have submitted PR ( https://github.com/conda-forge/cupy-feedstock/pull/24 ) and PR ( https://github.com/conda-forge/cupy-feedstock/pull/25 ) to add CUDA 10.2.

**Comment by atraining** [comment]
Hi guys, I have seen both merge requests are merged. Is there anything missing to support CUDA 10.2 or is this issue actually closed?

Thanks for the great work!

**Comment by jakirkham** [comment]
Have you tried installing it?

**Comment by atraining** [comment]
Not yet! I can verify it on Friday if you like.

**Comment by jakirkham** [comment]
Yeah the packages are built. I think we just need people to try them out and report back. So if that would be interesting to you, that would be very helpful 😀

**Comment by leofang** [comment]
ref: https://github.com/cupy/cupy/pull/2910#issuecomment-582802592

**Comment by jakirkham** [comment]
Thanks Leo! So should we backporting PR ( https://github.com/cupy/cupy/pull/2922 ) as a patch? Are there other things we should be doing?

**Comment by leofang** [comment]
For v6: I am not sure. There are two issues:
1. Are these patches (cupy/cupy#2910 and cupy/cupy#2922) safely applicable to v6? We don't have CI to confirm this. @kmaehashi, do you have any insight for this?
2. Are we  gonna maintain a patched version of v6 ourselves? I'd rather not, since we don't have CI...

For v7: both patches will be backported, so let's just wait for the new release.

I am not aware of other relevant patches. Will add here if I find any.

**Comment by jakirkham** [comment]
Ok, that seems reasonable. Thanks Leo! 😄

**Comment by leofang** [comment]
> For v7: both patches will be backported, so let's just wait for the new release.

Sorry @jakirkham @rlratzel for my oversight. With hindsight only one of the patches was backported, which is why we need #41.

**Comment by leofang** [comment]
Closing this issue as we already built CUDA support, and this issue is also addressed upstream. 

@atraining You can give it a try with the latest v7.3.0 that we just pushed to Conda-Forge.
