### ISSUE TITLE
Build CuPy for Arm64?

### ISSUE THREAD

**Issue by jamescrowley** [conda-forge/cupy-feedstock#176]
### Comment:

Apologies if this is the wrong place to raise this, but I found this previous issue - https://github.com/conda-forge/cupy-feedstock/issues/48 - which was closed as solved, but there doesn't seem to be an arm64 build of cupy on conda-forge. Am I missing something?

**Comment by leofang** [comment]
That's right, CuPy does not support macOS mainly because nvidia does not.
