### ISSUE TITLE
AttributeError: module 'cupyx.scipy' has no attribute 'signal'

### ISSUE THREAD

**Issue by bhezy** [conda-forge/cupy-feedstock#187]
### Comment:

Hello cupy-feedstock community!

I am running Windows 11 with a 3090, and have not been able to use 'signal' in 'cupyx.scipy'. I am running CUDA v=11.7. Any support would be much appreciated, as I need to perform fftconvolution and this is the most efficient implementation in theory for my use case.

If there is any information that is needed which I did not provide, please let me know! I am new to posting issues.

Best regards,
~ Ben

**Comment by kmaehashi** [comment]
You need an explicit import to use the module. `import cupyx.scipy.signal`

**Comment by bhezy** [comment]
@kmaehashi  that worked, thank you so much!!! Now, I am encountering an issue:
CompileException: nvrtc: error: failed to open nvrtc-builtins64_113.dll.
  Make sure that nvrtc-builtins64_113.dll is installed correctly.

Which has its own repo on StackOverflow:
https://stackoverflow.com/questions/68892447/cupy-error-failed-to-open-nvrtc-builtins64-101-dll

But no solution. It may be that it is searching for a version of Cuda that I do not have (11.3 instead of 11.7), Not sure how to go about tackling that. Either way, thank you!
