### ISSUE TITLE
Optional dependency on cupy?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/cupy-feedstock#193]
### Comment:

We have been trying to integrate cupy into our computing pipeline.

However, what is missing for us is a way to express the "dependency on cupy but only if you have a GPU".

Other packages like tensorflow and pytorch, that are installable for both CPU only systems and cuda enabled systems have a package that is always installable. We thus specify in our packages the `pytorch` dependency and let mamba resolve things.

Are there any recommendations for cupy? How do others do it?

cc: @kingbedjed

**Comment by leofang** [comment]
Is this question about how to craft your conda recipe to make CuPy an optional dependency (in the sense that it'd be installed in a GPU env)?

**Comment by hmaarrfk** [comment]
yes.

**Comment by jakirkham** [comment]
How about building two package variants one with `cupy` & `__cuda` and one without?

**Comment by leofang** [comment]
Hi @hmaarrfk, is this question addressed?

**Comment by hmaarrfk** [comment]
Yes.  Thank you

**Comment by hmaarrfk** [comment]
Like clockwork, 1 year later this dilemma pops up again for me.

I think I finally have a way to formulate it.

Consider a pure python package that could benefit from cupy acceleration. Given it is pure python, we aren't really adding ` __cuda` variant.

Therefore, I would like this pure python package to depend on cupy, but only if supported by the underlying hardware. A  `cupyifyoucan` package would be the "preferred way" for me.

If not sure if the package:
```
cupyifyoucan
```

would be an appropriate output of this feedstock (the name of course is up for debate).

But maybe this helps explain our usecase a little more.

**Comment by leofang** [comment]
@hmaarrfk I am not sure I understand. Right now, `__cuda` is listed as a `run_constrained` in `cupy-core`, so if there's no CUDA driver installed, it can be installed in a CPU-only env just fine. What would be missing here?

**Comment by hmaarrfk** [comment]
```

  Updating specs:

   - cupy=13
   - ca-certificates
   - certifi
   - openssl


  Package            Version  Build            Channel          Size
──────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────

  + fastrlock          0.8.2  py310hc6cd4ac_2  conda-forge      38kB
  + cuda-version        12.4  h3060b56_3       conda-forge      21kB
  + libnvjitlink     12.4.99  hd3aeb46_0       conda-forge      17MB
  + cuda-nvrtc       12.4.99  hd3aeb46_0       conda-forge      19MB
  + libcufft       11.2.0.44  hd3aeb46_0       conda-forge     175MB
  + libcurand     10.3.5.119  hd3aeb46_0       conda-forge      42MB
  + cupy-core         13.0.0  py310had4011e_3  conda-forge      40MB
  + libcusparse   12.3.0.142  hd3aeb46_0       conda-forge     118MB
  + libcublas      12.4.2.65  hd3aeb46_0       conda-forge     240MB
  + libcusolver    11.6.0.99  hd3aeb46_0       conda-forge      82MB
  + cupy              13.0.0  py310h7aad9d2_3  conda-forge     352kB

  Summary:

  Install: 11 packages

  Total download: 732MB

──────────────────────────────────────────────────────────────────────
```

You seem to be correct. `cupy` is installable even without a GPU.


I guess I was using `import cupy` as a test of whether or not cupy was even "usable" and as a sentinel that `cupy.zeros` would even work.

That is something I'll have to check the docs for.

I was trying to write code that is compatible with both cupy and numpy, but I wrongly assumed that just because cupy was importable, that it was "usable".

I should maybe try to call:
```
cupy.cuda.device.get_compute_capability()
```

before trying to execute cupy GPU code.

**Comment by leofang** [comment]
Right, I guess I see your confusion. Starting CuPy v13, it is made importable in all cases, including CPU-only environment. It was requested due to similar needs as you described (writing NumPy/CuPy compatible code to optionally support GPU). Any CUDA call as you described should be a good proxy to check if GPU is available at run time. If you think a better proxy is needed, please feel free to file an issue to CuPy.
