### ISSUE TITLE
Adding optional dependencies on CUDA 12

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cupy-feedstock#207]
Some of the optional dependencies were skipped on CUDA 12 as there were no packages for them at the time. Since these have gotten more filled out, maybe it is worth trying to readd them?

https://github.com/conda-forge/cupy-feedstock/blob/1788a9c9970bbf09e783d64e9fede420cb32b18f/recipe/meta.yaml#L140-L146

_Originally posted by @jakirkham in https://github.com/conda-forge/cupy-feedstock/pull/199#discussion_r1214730054_

**Comment by leofang** [comment]
hmmm I had a window opened last night trying to create an issue to track this, but it seems I forgot to add the green button... Sure, yes we should do it.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Tried adding just the `linux_64` CUDA 12 case in that re-render PR. Please let me know what you think 🙂
