### ISSUE TITLE
The bot failed to send CuPy v12.1.0 update

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#217]
The latest one was https://github.com/conda-forge/cupy-feedstock/pull/215, but after the that the bot fails to continue sending updates. Did we piss it off? 😂

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
It's also possible to [request an update from the bot]( https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-update-version )
