### ISSUE TITLE
Reactivate cuDNN support on CUDA 12 + aarch64/ppc64le when glibc 2.27+ is supported

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#224]
Right now it's deactivated 
https://github.com/conda-forge/cupy-feedstock/blob/bfc894722b3beead8ff4e53f1cfb4d7b01eff03a/recipe/meta.yaml#L150
due to the CF infrastructure not supporting newer glibc yet (https://github.com/conda-forge/cudnn-feedstock/issues/58).

**Comment by jakirkham** [comment]
After discussion, we relaxed the `__glibc` constraint in `cudnn`. More in details in issue: https://github.com/conda-forge/cudnn-feedstock/pull/80

In any event this should be unblocked now

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render
