### ISSUE TITLE
`%CUDA_PATH%` activation on Windows

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cupy-feedstock#232]
Currently on Windows we set `%CUDA_PATH%` to `%CONDA_PREFIX%`

https://github.com/conda-forge/cupy-feedstock/blob/11d783c60f134a359f8b617bf21cc748b8463c90/recipe/activate.bat#L10

However it appears when users run with this this, they get [`CUDA_PATH` detection warnings]( https://github.com/cupy/cupy/blob/cf9b4a517725b803fba4828ed0b1c93a231cc5da/cupy/_environment.py#L214-L216 ). Though they seem to be able to use CuPy without issues

Since the headers and includes from the CTK typically are installed to `%CONDA_PREFIX%\Library`, wonder if we should update this to point to that location

```diff
-set "CUDA_PATH=%CONDA_PREFIX%"
+set "CUDA_PATH=%CONDA_PREFIX%\Library"
```

Though looking at [this logic in CuPy]( https://github.com/cupy/cupy/blob/cf9b4a517725b803fba4828ed0b1c93a231cc5da/cupy/_environment.py#L204-L210 ), am not sure if we should point to `%CONDA_PREFIX%\Library\bin` instead

Thoughts?

**Comment by jakirkham** [comment]
It's worth noting there is also some discussion about updating or dropping the activation script ( https://github.com/conda-forge/cupy-feedstock/issues/206 ), which might also affect how this is handled

**Comment by leofang** [comment]
Let us move the discussion to #206, I think it's the same issue.

**Comment by leofang** [comment]
See https://github.com/conda-forge/cupy-feedstock/issues/206#issuecomment-1819832486.

**Comment by jakirkham** [comment]
Ok I read that as Linux whereas the issue here is Windows

The `targets` point specifically doesn't apply to Windows

On Windows, we have a more similar CTK structure between CUDA 11 / 12

**Comment by leofang** [comment]
> Ok I read that as Linux whereas the issue here is Windows
> 
> The `targets` point specifically doesn't apply to Windows
> 
> On Windows, we have a more similar CTK structure between CUDA 11 / 12

To CuPy the same applies to Linux as well. All headers and shared libraries can be found in the targets directory, enough to ensure a fully functional CuPy.

**Comment by jakirkham** [comment]
Ok let's close then
