### ISSUE TITLE
Manually migrate for Python 3.12

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#234]
For some reason the bot shows errors.

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Did a little reading. FWICT it looks like the bot was [unable to solve the dependencies]( https://github.com/regro/cf-scripts/actions/runs/7408339550/job/20156340039#step:8:7686 ). Relevant snippet below:

```
  Could not solve for environment specs
  The following package could not be installed
  └─ cusparselt 0.2.0.1.* 1 does not exist (perhaps a typo or a missing channel).
```

**Comment by leofang** [comment]
@jakirkham @beckermr the PY312 migration status still says cupy is not solvable, despite I manually added the migrator (#235). It's unclear to the why the bot would complain about `cusparselt`. I checked on anaconda.org and saw the package is still there. Any clue if this is a disguise of other issues?

**Comment by beckermr** [comment]
Could be for sure. We should add a test case to the solver test package and figure out when we have time.

**Comment by jakirkham** [comment]
Not to speak for Matt, but you could mark it done by making a PR similar to this one ( https://github.com/regro/cf-graph-countyfair/pull/7 )

**Comment by leofang** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Maybe this is relevant ( https://github.com/conda-forge/cupy-feedstock/pull/238 )?

**Comment by jakirkham** [comment]
Unfortunately that didn't work, trying a different approach with PR ( https://github.com/conda-forge/cupy-feedstock/pull/240 )

**Comment by leofang** [comment]
I'd love to get the bot bug fixed, but it seems we're still clueless. I had to disable the `cusparselt` support (https://github.com/conda-forge/cupy-feedstock/pull/244) to make the bot happy. It finally works (migration is propagated to downstream: https://github.com/conda-forge/cuquantum-feedstock/pull/54). Is there anything else we should do before closing this issue?

**Comment by jakirkham** [comment]
Think we should take a closer look at this list and see how we can cut that down

https://github.com/conda-forge/cupy-feedstock/blob/197bc441732ce3a3bc7086e1648796637992eda8/recipe/meta.yaml#L143-L168

Ideally we would get that down to build tools only. Atm there's quite a few libraries in there

Am sure there is some history I'm forgetting here (perhaps issues early on in CUDA 12 that have since been fixed?), but it may be worth revisiting

**Comment by leofang** [comment]
They are needed because of CuPy's autotool-like build system, which requires executable/linkable objects native to the build environment. Nothing has changed, and redundancy has been pruned.

**Comment by jakirkham** [comment]
Wanted to see what would happen (even if only to see errors)

xref: https://github.com/conda-forge/cupy-feedstock/pull/246

**Comment by hmaarrfk** [comment]
this can be closed correct?

**Comment by jakirkham** [comment]
In terms of the feedstock being migrated for Python 3.12, yes that was done a long time ago

In terms of the bot errors, don't recall whether we were able to resolve those. We certainly tried lots of things that didn't end up working

**Comment by leofang** [comment]
Let's just close this since it is not going anywhere...
