### ISSUE TITLE
Retry using VS2019

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cupy-feedstock#250]
Almost a year ago, 15ab48209a3d3714e30858524c00f3c4395ab271 went back to VS2017 due to some apparent issues at the time. It would be good to remove
https://github.com/conda-forge/cupy-feedstock/blob/95b2a2daefc4272c3d29a5898bcf11bfe64cd3af/recipe/conda_build_config.yaml#L1-L4

and just use the conda-forge default compilers, as cupy is among the last feedstocks in conda-forge to still use VS2017.

This is hopefully easier now with the intervening work to update CUDA versions (and drop <11.2)? 🤞

**Comment by h-vetinari** [comment]
Thanks for the quick response!

**Comment by leofang** [comment]
Thanks @h-vetinari for reminder, this was on my backburner. I still don't know how/when the bug that forced us to stay on vs2017 was fixed, but it seems working out just fine!
