### ISSUE TITLE
Thrust/CUB version inconsistent in `cupy-core`

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#259]
```
$ python -c "import cupy as cp; cp.show_config()"
...
Thrust Version               : 200001
CUB Build Version            : 200200
...
```
based on:
```
$ conda list cupy
# packages in environment at /home/leof/miniforge3/envs/cuqnt_dev_py311_cu12:
#
# Name                    Version                   Build  Channel
cupy-core                 13.0.0          py311h84cfafc_3    conda-forge
```

**Comment by leofang** [comment]
(noticed this when triaging https://github.com/cupy/cupy/issues/8249...)

**Comment by jakirkham** [comment]
How does that version information get generated?

**Comment by leofang** [comment]
IIRC one is from parsing the header and another from parsing the git history, but I need some time to dig deeper

**Comment by leofang** [comment]
This seems to happen only with `cupy-core` 13.0.0 and not with newer versions. I also inspected the code and couldn't understand how this could happen. Let's close this issue for now...
