### ISSUE TITLE
Use CUDA 12.4 to build CuPy

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#265]
This is what CuPy v13.1.0 upstream wheels did. We should follow.

**Comment by jakirkham** [comment]
Maybe we can implement a similar strategy as we used in `cuda-python` to get the latest CUDA 12 ( https://github.com/conda-forge/cuda-python-feedstock/commit/54a6579b17930f8184414e0c9212d29e561dd591 )

**Comment by leofang** [comment]
Sounds good, @jakirkham do you think you can piggyback this in your PR #266 so that we can make all changes in one shot and rebuild?

**Comment by jakirkham** [comment]
Would prefer these be done in separate PRs

**Comment by leofang** [comment]
@conda-forge-admin, please rerender
