### ISSUE TITLE
Pulling 7.1.0

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cupy-feedstock#31]
It appears there was a pretty serious bug in CuPy 7.1.0. ( https://github.com/cupy/cupy/issues/2971 ) Would like to pull the packages from conda-forge so that others don't run into this issue. Thoughts?

**Comment by leofang** [comment]
https://github.com/cupy/cupy/issues/2971#issuecomment-575402543

**Comment by leofang** [comment]
Please feel free to delete the published packages if you want. Either way, I would add a patch in the recipe to fix it.

**Comment by jakirkham** [comment]
We don’t normally delete packages, but we do move them to the `broken` label if there are issues. It’s still possible for people to opt to install the package that way.

Adding a patch and rebuilding is a quite common solution. This would be a good solution if it seems agreeable.

**Comment by leofang** [comment]
Let me try putting together a patch PR.

**Comment by jakirkham** [comment]
Sounds good. Thanks Leo! 😄

**Comment by leofang** [comment]
> but we do move them to the `broken` label if there are issues.

@jakirkham How do we maintainers do this?

**Comment by jakirkham** [comment]
Unfortunately there is not a way currently. It's definitely a request we have with Anaconda.

**Comment by jakirkham** [comment]
Though I should say that the usual approach (currently) is maintainers ask `@conda-forge/core` to assist with moving the packages to `broken`.

**Comment by jakirkham** [comment]
FWIW I've gone ahead and marked 7.1.0 packages from yesterday as `broken`. After all we have included the patch in the new builds and they already can be downloaded. Please let me know if I missed any or got any incorrectly. 🙂

**Comment by leofang** [comment]
Thanks for doing this, John! I think you tagged it right.
