### ISSUE TITLE
Disable CUB support temporarily?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#38]
Given the recurring CUB bugs that went undetected in the recent releases (there was a hot fix in v7.1.1, and now v7.2.0 has a bug too: cupy/cupy#3092), I propose we remove the CUB support from the package until PFN bundles it and includes tests in their CI, i.e. when #20 is resolved. 

@jakirkham If this is OK with you I'll make a PR.

**Comment by jakirkham** [comment]
Yeah let’s do it 🙂

**Comment by jakirkham** [comment]
Should we mark the packages with CUB as `broken`?

**Comment by leofang** [comment]
Oh yes, please. Sorry you had to do this manually (?) I wish I could do this too...

**Comment by jakirkham** [comment]
Ah not any more. We now have a workflow anyone can use! 😄

A few people have used it successfully. Docs are a bit sparse. Basically we add the packages to a list in a PR to [this repo]( https://github.com/conda-forge/cf-mark-broken ). Once merged they are marked `broken`.

**Comment by leofang** [comment]
Neat! Thanks a lot, John. Let me try it.

**Comment by jakirkham** [comment]
Of course. Thanks Leo. Please let me know if you have any questions 🙂

**Comment by jakirkham** [comment]
Marked `broken` with PR ( https://github.com/conda-forge/cf-mark-broken/pull/10 ).
