### ISSUE TITLE
Support cuTENSOR

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#57]
According to cuTENSOR license the `.so` and `.h` files are redistributable: 
> 2. Distribution. The following portions of the SDK are distributable under the Agreement: the runtimes files ending with .so and .h as part of your application.

I suppose the package should be added upstream. Then, we just add `cutensor` to our dependencies, and set `CUTENSOR_PATH` to $PREFIX prior to building.

I was able to build cuTENSOR support with our experimental self-hosted agent, but ~~I don't know how to include its files in the package.~~ **(UPDATE)** the module is not importable, see my comment below.

**Comment by leofang** [comment]
@jakirkham I think the glibc version used in CF's docker images (condaforge/linux-anvil-cuda:10.0 etc) is too old (2.12); cuTENSOR requires at least 2.14:
https://dev.azure.com/nsls2forge/nsls2forge/_build/results?buildId=2526&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=2413

**Comment by leofang** [comment]
cc: @jjhelmus

**Comment by jjhelmus** [comment]
The [CUDA Toolkit 10.0 release notes](https://docs.nvidia.com/cuda/archive/10.0/cuda-toolkit-release-notes/index.html#deprecated-features) indicated that support for RHEL 6.x was deprecated and may be dropped in a future release.  I would not be surprised if cuTENSOR did not support RHEL 6.x.

RHEL 6 / CentOS 6 use glibc 2.12, the later is the base for the `conda-forge/linux-anvil-cuda:10.0 image`.

**Comment by leofang** [comment]
Thanks, @jjhelmus! Does it mean that to enable cuTENSOR support here we should
1. Update conda-forge's CUDA dockers to CentOS 7
2. Package cuTENSOR and upload to Anaconda

**Comment by leofang** [comment]
> 1. Update conda-forge's CUDA dockers to CentOS 7

This is brought to upstream: https://github.com/conda-forge/docker-images/issues/137.

**Comment by leofang** [comment]
cuTENSOR can help `cupy.sum()`: cupy/cupy#2939

**Comment by jakirkham** [comment]
We are working on getting CentOS 7 up and running in conda-forge, but there are a few moving parts involved. So won't be done overnight, but we are working on it 😉

**Comment by leofang** [comment]
Closed by #94 (master) and #95 (rc).

**Comment by leofang** [comment]
(What a long journey we've been through!)
