### ISSUE TITLE
Test should run should report why it failed, regardless of whether a gpu is around

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/cupy-feedstock#6]
Build should show why the ImportError happened

**Comment by leofang** [comment]
CuPy tests cannot be run without a GPU. I don't think the CI infrastructure has GPUs, am I right @jakirkham?

**Comment by leofang** [comment]
Yeah usually we want to know which module is broken. Say I remove `cupy.cuda.cufft` manually, this is what we want to see:
```shell
$ python -c "import cupy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leofang/cupy_cub/cupy/__init__.py", line 53, in <module>
    from cupy import fft  # NOQA
  File "/home/leofang/cupy_cub/cupy/fft/__init__.py", line 1, in <module>
    from cupy.fft.fft import fft  # NOQA
  File "/home/leofang/cupy_cub/cupy/fft/fft.py", line 8, in <module>
    from cupy.cuda import cufft
ImportError: cannot import name 'cufft' from 'cupy.cuda' (/home/leofang/cupy_cub/cupy/cuda/__init__.py)
```

**Comment by leofang** [comment]
CuPy's import error message itself is indeed not very informative for package maintainers:
https://github.com/cupy/cupy/blob/6fd547c12dcb6e912e16fd9ae833d8259516c575/cupy/__init__.py#L11-L36

**Comment by jakirkham** [comment]
> Yeah usually we want to know which module is broken. Say I remove `cupy.cuda.cufft` manually, this is what we want to see:

Right. This we can [do without importing]( https://github.com/conda-forge/cupy-feedstock/blob/efe21e550dc3b8af272886fafa4374a76b82e790/recipe/run_test.py#L7 ), which is handy as we can do this as part of the package build on CI here. We can add more such checks as needed.

My guess is the problem Marius is running into is more nuanced than a missing module, but I could be wrong.

> CuPy's import error message itself is indeed not very informative for package maintainers

Good point. Then PR ( https://github.com/conda-forge/cupy-feedstock/pull/8 ) is probably not what we want.

**Comment by leofang** [comment]
Reading the issue title again: 
> Test should run should report why it failed, regardless of whether a gpu is around

Since I'm sure without a GPU the tests cannot be run, I'm closing this issue now. 

Marius, please feel free to reopen this issue if you can provide more info for what you expect. Thanks.

**Comment by jakirkham** [comment]
I know we talked about this @mariusvniekerk, but I sadly don't remember what the intended outcome was. Do you just want to see the traceback or something?
