### ISSUE TITLE
Build CuPy for Windows?

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#62]
I think cupy/cupy#3403 would not be an issue if CuPy is installed from conda-forge instead of PyPI. Unfortunately I don't think conda-forge provides the CUDA toolchain on Windows yet.

**Comment by leofang** [comment]
I think this is possible with https://github.com/conda-forge/cudatoolkit-feedstock, at least we can build a minimum package without extra dependencies like cuDNN or NCCL.

**Comment by jakirkham** [comment]
Yeah we would also need to figure out issue ( https://github.com/conda-forge/nvcc-feedstock/issues/48 ).

**Comment by jaimergp** [comment]
We are definitely doing this for OpenMM, so happy to participate in a joint PR or something similar!

**Comment by leofang** [comment]
Two quick notes:
1. The bot hasn't generated a new PR since #89 was closed yesterday.
2. I would like to publish Windows packages after most Windows errors are resolved (work is ongoing).

cc: @kmaehashi

**Comment by jakirkham** [comment]
cc @conda-forge/bot

**Comment by CJ-Wright** [comment]
hmm, the latest PR is set as `never issued`, which usually means the rerender produced the same result with/without the migration. https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/cupy.json#L575

If I had to guess, maybe the rerender is balking at the `run_constrained` being empty?

**Comment by leofang** [comment]
Thanks @CJ-Wright, I can look into it later. Is this a log generated by the bot?
https://github.com/regro/cf-graph-countyfair/blob/028676daf89c60caf5d6ecd496582e26e9fb3542/node_attrs/cupy.json#L4271
> "windows_cuda": "not solvable: master: ['linux_64_cuda_compiler_version11.0python3.6.____73_pypy: Encountered problems while solving.\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'linux_64_cuda_compiler_version11.0python3.6.____cpython: Encountered problems while solving.\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'linux_64_cuda_compiler_version11.0python3.7.____cpython: Encountered problems while solving.\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'linux_64_cuda_compiler_version11.0python3.8.____cpython: Encountered problems while solving.\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'linux_64_cuda_compiler_version11.0python3.9.____cpython: Encountered problems while solving.\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'win_64_cuda_compiler_version10.0python3.6.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.0python3.7.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.0python3.8.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.0python3.9.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.1python3.6.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.1python3.7.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.1python3.8.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.1python3.9.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.2python3.6.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.2python3.7.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.2python3.8.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version10.2python3.9.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\n', 'win_64_cuda_compiler_version11.0python3.6.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'win_64_cuda_compiler_version11.0python3.7.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'win_64_cuda_compiler_version11.0python3.8.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n', 'win_64_cuda_compiler_version11.0python3.9.____cpython: Encountered problems while solving.\\nProblem: nothing provides requested nccl 2.7.8.1.*\\nProblem: package cudnn-7.6.5-cuda10.0_0 requires cudatoolkit >=10.0,<10.1, but none of the providers can be installed\\n']"

**Comment by CJ-Wright** [comment]
That should have made cupy not solvable, but currently it is listed as done. You could try to make the PR manually by copying over the migration file and rerendering.

**Comment by leofang** [comment]
> I checked it locally and you are right that rerendering is not changing anything even with the migration file copied manually. Is it because we have a `conda_build_config.yaml`?

Now that I am a bit more experienced with manipulating CBC, I think the answer is yes.

**Comment by leofang** [comment]
Back to the main issue, I'd like to build Windows support for the upcoming v9.0.0rc1. I've been doing some bug fixing for Windows (despite I have no access to a Windows+CUDA machine) and hopefully we can get ready by the end of this month (code freeze for rc1).
