### ISSUE TITLE
Need post-link and pre-unlink scripts

### ISSUE THREAD

**Issue by leofang** [conda-forge/cupy-feedstock#66]
https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html

I noticed we need to fix the following situations:
- After the package is installed, `CUDA_PATH` that we set should be made immediately available without a deactivate/activate cycle.
- Before the package is uninstalled, `CUDA_PATH` should be either unset or restored to the old value.

**Comment by leofang** [comment]
Would be nice to fix packages since 7.3.0, but I don't have time this week 😅

**Comment by jakirkham** [comment]
I thought this is what we were accomplishing with the activate/deactivate scripts, right? Or am I missing something?

**Comment by leofang** [comment]
Apparently they are different and I missed it too 😅 For example, the activate script doesn't get executed when you're already in the targe environment and install the package; it's only executed during `conda activate my_env`. To have the desired effect enabled immediately after installation, the post-link script must be used. Likewise for deactivate vs pre-unlink.

**Comment by jakirkham** [comment]
What version of Conda are you using?

**Comment by leofang** [comment]
4.7.12

**Comment by jakirkham** [comment]
I think at some point they made it so activation automatically occurs after an install (that's what I've seen at least), but I don't recall when that change occurred. It may be worth upgrading (if you can).

**Comment by leofang** [comment]
Oh, that's good to know! Will test and close this issue if it works. Thanks John.

**Comment by leofang** [comment]
OK I tested it. So,

> * After the package is installed, `CUDA_PATH` that we set should be made immediately available without a deactivate/activate cycle.

This is correctly done even in 4.7.12, so we're good and do not need a post-link script.

> * Before the package is uninstalled, `CUDA_PATH` should be either unset or restored to the old value.

This is not done. After cupy is uninstalled, the `CUDA_PATH` set by us cannot be a residual, so we need a pre-unlink script that executes the content of our deactivate script.

**Comment by jakirkham** [comment]
According to [this line]( https://github.com/conda/conda/blob/b200354f6358696fc25e382ca208daaff3f59d24/conda/shell/etc/profile.d/conda.sh#L80) reactivation should happen during removal. Are we sure there isn't a bug in our deactivation script or possibly Conda itself?

**Comment by leofang** [comment]
btw I think I wasn't 100% correct.
 
> > * After the package is installed, `CUDA_PATH` that we set should be made immediately available without a deactivate/activate cycle.
> 
> This is correctly done even in 4.7.12, so we're good and do not need a post-link script.

A new `CUDA_PATH` is set, yes. But in this case if `CUDA_PATH` is already set prior to `conda install cupy`, then the old value isn't cached to `CONDA_CUPY_CUDA_PATH` as I intended. I feel when the environment is reactivated, conda does not see all of the env variables. From the shell script to which you linked I wasn't able to tell where it went wrong, but conda could be to blame...

**Comment by leofang** [comment]
I could not reproduce this, closing for now.
